### ISSUE TITLE
Make repo public

### ISSUE THREAD

**Issue by jim-hill-r** [NavAbility/NavAbilityCaesarExtensions.jl#10]

**Comment by dehann** [comment]
alright, it's public.  Jim, I'll leave the issue open to confirm you have full access.

**Comment by jim-hill-r** [comment]
Thanks for making it public. Still can't change visibility. It is not a repo setting. It is an Organization setting. Even if I am admin on repo, the org setting supercedes it.

![image](https://user-images.githubusercontent.com/25872250/156942177-1a13a00b-e1c8-4106-82c0-9bdc67575355.png)

**Comment by dehann** [comment]
Oh... I tried to find where to set that but didn't find.  @GearsAD , do you perhaps know how to set Jim admin access in Org NavAbility team so he can have access to a repo he created :-P

**Comment by jim-hill-r** [comment]
It's not a user specific problem. It's an org problem. https://docs.github.com/en/organizations/managing-organization-settings/restricting-repository-visibility-changes-in-your-organization

**Comment by dehann** [comment]
Alright, finally i got it, thanks!

![Uploading Screenshot from 2022-03-06 16-05-06.png…]()
